version: '3'

networks:
  docker-microservice-tool-stack_webnet:
    external: true

services:
  openliberty:
    build: .
    ports:
      - "8080:9080"
      - "9443:9443"
    volumes:
     - C:\etc\opt:/etc/opt
    networks:
    - docker-microservice-tool-stack_webnet
    hostname: "text-analysis-project"
