version: '3'

networks:
  web:
    driver: bridge
  serv:
    driver: bridge

services:
  webapp:
    build: ./text-analysis-webapp
    ports: 
      - "8080:80"
    networks:
    - web
    hostname: "text-analysis-webapp"
  webservice:
    build: ./text-analysis-service
    ports: 
      - "9990:9990"
    networks:
    - serv
    hostname: "text-analysis-service"