version: '3'

networks:
  docker-microservice-tool-stack_webnet:
    external: true

services:
  payara:
    build: .
    ports:
      - "8080:8080"
      - "4848:4848"
    volumes:
     - C:\etc\opt:/etc/opt
    networks:
    - docker-microservice-tool-stack_webnet
    hostname: "text-analysis-project"
