version: '3'

networks:
  dev:
    driver: bridge

services:
  webapp:
    build: ./text-analysis-webapp
    ports: 
      - "8181:80"
    networks:
    - dev
    hostname: "text-analysis-webapp"
  webservice:
    build: ./text-analysis-service
    ports: 
      - "8080:8080"
    networks:
    - dev
    hostname: "text-analysis-service"